# Generated by Django 5.2.8 on 2025-12-30 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('minor', 'minor'), ('medium', 'medium'), ('high', 'high'), ('critical', 'critical')])),
                ('file', models.FileField(default='default.jpg', upload_to='incidents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Incidents',
                'db_table': 'incident',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('profile', models.ImageField(default='default.jpg', upload_to='photos/')),
            ],
            options={
                'verbose_name_plural': 'The_Users',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_notes', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='myapp1.incident')),
            ],
            options={
                'verbose_name_plural': 'Incident Reports',
                'db_table': 'incident_report',
            },
        ),
        migrations.CreateModel(
            name='IncidentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_title', models.CharField(blank=True, max_length=100)),
                ('action_type', models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('deleted', 'Deleted')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='myapp1.incident')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp1.user')),
            ],
        ),
        migrations.AddField(
            model_name='incident',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.user'),
        ),
    ]
